//Purpose: To prepare the database and define the tables.

import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:drift/web.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'daos/invoice_dao.dart'; // 1. تأكد من استيراد ملف الـ DAO

part 'database.g.dart'; // File automatically generated by Drift

// Define the invoice table
class Invoices extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get customerName => text()();
  DateTimeColumn get date => dateTime().clientDefault(() => DateTime.now())();
  RealColumn get total => real()();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();
}

// Database definition
@DriftDatabase(tables: [Invoices], daos: [InvoiceDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    if (kIsWeb) {
      // Use WebDatabase for web platform
      return WebDatabase('erp.db');
    } else {
      // Use SQLite for desktop platforms (Windows, macOS)
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, 'erp.db'));
      return NativeDatabase(file);
    }
  });
}

// Open a connection with SQLite
// LazyDatabase _openConnection() {
//   return LazyDatabase(() async {
//     if (kIsWeb) {
//       //  This will work on Chrome
//       return drift_web.WebDatabase('erp.db');
//     } else {
//       //  This will work on Android, iOS, Desktop
//       final dbFolder = await getApplicationDocumentsDirectory();
//       final file = File(p.join(dbFolder.path, 'erp.db'));
//       return NativeDatabase(file);
//     }
//   });
// }
//
