targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
      build_web_compilers:ddc:
        options:
          # Enable debug symbols for drift workers
          dart2js_args:
            - --no-minify
            - -O2 