//Purpose: To prepare the database and define the tables.

import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter/foundation.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'daos/invoice_dao.dart'; // 1. تأكد من استيراد ملف الـ DAO

part 'database.g.dart'; // File automatically generated by Drift

// Define the invoice table
class Invoices extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get customerName => text()();
  DateTimeColumn get date => dateTime().clientDefault(() => DateTime.now())();
  RealColumn get total => real()();
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();
}

// Database definition
@DriftDatabase(tables: [Invoices], daos: [InvoiceDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      await m.createAll();
    },
    onUpgrade: (Migrator m, int from, int to) async {
      // Add migrations here when schema version changes
    },
    beforeOpen: (details) async {
      // Add any initialization logic here
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'erp.db'));
    return NativeDatabase.createInBackground(file);
  });
}

// Add this method to your database class
Future<String> getDatabasePath() async {
  final dbFolder = await getApplicationDocumentsDirectory();
  final file = File(p.join(dbFolder.path, 'erp.db'));
  debugPrint('Database path: ${file.path}');
  return file.path;
}

// Add this method to your database class
Future<void> deleteDatabase() async {
  final dbFolder = await getApplicationDocumentsDirectory();
  final file = File(p.join(dbFolder.path, 'erp.db'));
  if (await file.exists()) {
    await file.delete();
    debugPrint('Database deleted successfully');
  }
}
